defaults:
  - _default_
  - _self_

name: bridge_onpolicy
script_module: bridge_onpolicy

loss_type: "d2e-ipf"

num_sb_steps: 50
num_fwd_steps: 2500
num_bwd_steps: 2500

num_sampling_steps: 20
ref_process_logits_bias: 3.5
alpha_milestones: [5, 10, 15]
alpha_values: [0.6, 0.8, 1.0]
alpha_start: 0.4

batch_size: 256
num_trajectories: 2

fwd_lr: 1e-4
fwd_weight_decay: 0.0001

bwd_lr: 1e-3
bwd_weight_decay: 0.0001